//! GENERATED by `todo/store-cross/gen_zig_embed.py` — do not edit by hand.
//!
//! The comptime `@embedFile` table for the schema-v2 fixture root (decision
//! C-D4).  Rows are in MANIFEST.tsv order.  A row whose blob is missing from
//! the fixture root is a COMPILE error, which is the strongest possible "the
//! sync step was never run"; the converse — a blob nobody embeds — is caught
//! at runtime by the three-way set equality in `src/xfixtures/xfix.zig`,
//! because this file and the manifest are not independent enough to grade
//! each other.

const Blob = @import("xfix.zig").Blob;

pub const blobs = [_]Blob{
    .{ .name = "wal3-java-tail.x.wal.0000000000000001.gz", .gz = @embedFile("data-v2/wal3-java-tail.x.wal.0000000000000001.gz") },
    .{ .name = "wal3-java-tail.x.wal.0000000000000002.gz", .gz = @embedFile("data-v2/wal3-java-tail.x.wal.0000000000000002.gz") },
    .{ .name = "wal3-java-cleaned.x.wal.0000000000000003.gz", .gz = @embedFile("data-v2/wal3-java-cleaned.x.wal.0000000000000003.gz") },
    .{ .name = "wal3-java-cleaned.x.wal.0000000000000004.gz", .gz = @embedFile("data-v2/wal3-java-cleaned.x.wal.0000000000000004.gz") },
    .{ .name = "wal3-zig-tail.x.wal.0000000000000001.gz", .gz = @embedFile("data-v2/wal3-zig-tail.x.wal.0000000000000001.gz") },
    .{ .name = "wal3-zig-tail.x.wal.0000000000000002.gz", .gz = @embedFile("data-v2/wal3-zig-tail.x.wal.0000000000000002.gz") },
};
